name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmUwMGQ5NmYtN2YyOC00NGFhLWEyZjQtZmRhYjE1NzE0ZjE2IiwidGVuYW50X2lkIjoiNzk5MzFiYjc5ZDVlNzJiMjYzOTdjZDUxZTlkNzk5ZDUxMzhlNWZmYzc3NzI0NTg3ODFlYWVjZWIwMGJmN2I5ZiIsImludGVybmFsX3NlY3JldCI6IjQ0ZTZmNzZmLThlMzQtNDUxMC05NzI5LWI3YWUwODcwNTE2OSJ9.wJWLart7H9TDhh_6BgCr6PH_RSxIQFOwIweMLmvbk_o"
SECRET_KEY = "Mythriisaslut@69"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
